# Generated by Django 5.1 on 2024-08-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_newslatter'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_view',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
